BASE_URL = 'localhost:5000'

SQLALCHEMY_DATABASE_URI = "sqlite:///./app.db"
EAUTH_USER_MODEL = 'app.models.User'
EAUTH_ENABLE_EMAIL_CONFIRM = False

EAUTH_FORM_REGISTER = 'app.forms.RegisterForm'
EAUTH_TEMPLATE_REGISTER = ('register.html', {})

EAUTH_ON_FINISH_REGISTER = '/'
EAUTH_ON_FINISH_LOGOUT = '/login'
EAUTH_ON_FINISH_REQUEST_RESET = '/'
EAUTH_DEFUALT_NEXT_URL  = '/private'

ENABLE_CSRF = True
SECRET_KEY = 'some_secret'
SQLALCHEMY_TRACK_MODIFICATIONS = True
